version: '3.8'

services:
  reverse_ssh:
    image: reversessh/reverse_ssh
    ports:
      - "2222:2222"
    env_file:
      - rssh.env
    volumes:
      - ./data:/data
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./logs/nginx:/var/log/nginx/"
      - "/etc/letsencrypt/live/rose.ubiquityrobotics.com/:/etc/letsencrypt/live/rose.ubiquityrobotics.com/:ro"
      - "/etc/letsencrypt/archive/rose.ubiquityrobotics.com/:/etc/letsencrypt/archive/rose.ubiquityrobotics.com/:ro"
